### ISSUE TITLE
Include Region in applicant metadata

### ISSUE THREAD

**Issue by andrewxhill** [keyko-io/filecoin-verifier#69]
Most Notaries applied for region specific focus, so it would help to point applicants to the right notary to assess their application. It's a bit tricky since it may include where their org is based, where their technology runs or is sold, and where their customers are based... so may even be multiple fields. cc @jnthnvctr

**Comment by josepablofm78** [comment]
As a first step to help with this situation, now the Request formulary includes a drop down that allows the clients to select the Region they are based on. This value generates a label in the issue, so the Notaries can filter the issues by the values of this label

![Captura de pantalla 2021-02-12 a las 15 21 06](https://user-images.githubusercontent.com/45420891/107779869-42c0c500-6d46-11eb-9ed1-ce78c9caa6bd.png)
