### ISSUE TITLE
Datacap not removed for Notary f019669

### ISSUE THREAD

**Issue by josepablofm78** [keyko-io/filecoin-verifier#76]
governance team agreed to remove datacap from notary  f019669/f1arlxnqbq2bpyw7wzcz7stnsr4v24xuwaj7p2uhq assigning 0TiB as datacap:

https://github.com/filecoin-project/notary-governance/issues/87

The messages sent to the network to propose/approve this 0TiB of allocation are:
https://filfox.info/en/message/bafy2bzacebmasrgxf3cpemeqb4xjetqzp5m7mlsggyitbjkgbvgc43a5jdhdy
https://filfox.info/en/message/bafy2bzacecihjsx3ly6mpvtcguiutawnul4vdm56fl72c67griq2rgtgjzjec

but somehow this notary still have some amount of datacap:

![Captura de pantalla 2021-03-17 a las 13 51 21](https://user-images.githubusercontent.com/45420891/111471189-eaa42680-8728-11eb-9ec5-5254e9e2c430.png)

It would be needed to track this messages to check that the proposal was sent correctly, and if so try to understand why this notary still have datacap

**Comment by mrsmkl** [comment]
Looks like it errors here https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/verifreg/verified_registry_actor.go#L70
I'll add the method to just remove datacap.
